// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/validate_version.test.ts.

/** The version of the `@rljson/validate` package. */
export const validateVersion = '0.0.12';
